EXPERIMENT_NAME: "vivit"

MODEL:
  NAME: "vivit"
  ARCH: "vivit"
  NUM_CLASSES: 400
  USE_CHECKPOINT: False

TRAIN:
  EPOCH: 100
  LR_BASE: 1e-3
  EVAL_FREQ: -1

  LR_SCHEDULER:
    DECAY_RATE: 0.1
    DECAY_EPOCH: 10

DATA:
  BATCH_SIZE: 2
  NUM_WORKER: 56